name: Publish
on:
  workflow_run:
    workflows: [CI]
    branches:
      - master
      - next
    types: [completed]

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write # publish a GitHub release
      issues: write # to released issues
      pull-requests: write # to released pull requests
      id-token: write # OIDC for npm provenance
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      # - run: pnpm install --no-frozen-lockfile
      # - run: pnpm install

      # * DISPLAY BRANCHES
      - name: Display Branches
        run: |
          echo "Checkout Branch: $(git rev-parse --abbrev-ref HEAD)"
          echo "Workflow Triggered Branch: ${{ github.event.workflow_run.head_branch }}"
          echo "Default Branch: ${{ github.event.workflow_run.head_branch }}"

      # - name: Npm Audit Signartures
      #   run: npm audit signatures

      # * AUTHENTICATE NPM
      - name: Authenticate Npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_RETESTIFY_TEST_NTS_TOKEN }}" > ~/.npmrc

      # * SEMANTIC RELEASE PUBLISH
      - name: Semantic Release Publish
        run: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RETESTIFY_TEST_NTS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_RETESTIFY_TEST_NTS_TOKEN }}
